#!/usr/bin/env python3
"""
04_identify_species_genus_specific_kmers.py

Identify species- and genus-specific k-mers by cross-comparing all reference
mitochondrial genomes.

Input is the k-mer table generated by 02_generate_52bp_kmers.py.

Definition used here
--------------------
species_specific:
    the k-mer occurs only in one species across the reference panel.

genus_specific:
    the k-mer occurs only in one genus across the reference panel.
    A species-specific k-mer is also genus-restricted, but by default it is
    reported as species_specific to avoid duplication.

Example
-------
python scripts/design/04_identify_species_genus_specific_kmers.py \
  --kmers results/design/02_kmers/reference_panel.52bp_kmers.tsv.gz \
  --out results/design/04_informative_kmers/species_genus_specific_kmers.tsv.gz \
  --summary results/design/04_informative_kmers/species_genus_specific_kmers.summary.tsv
"""

from __future__ import annotations

import argparse
import csv
import gzip
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Set


def open_text(path, mode="rt"):
    path = str(path)
    return gzip.open(path, mode) if path.endswith(".gz") else open(path, mode, newline="" if "t" in mode else None)


def clean_taxon(x: str) -> str:
    return str(x or "").strip()


def main() -> None:
    p = argparse.ArgumentParser(description="Identify species- and genus-specific k-mers.")
    p.add_argument("--kmers", required=True, help="K-mer TSV.GZ from 02_generate_52bp_kmers.py.")
    p.add_argument("--out", required=True, help="Output informative k-mer TSV or TSV.GZ.")
    p.add_argument("--summary", default=None, help="Optional summary TSV.")
    p.add_argument("--include-genus-even-if-species-specific", action="store_true",
                   help="Also label species-specific k-mers as genus_specific in an extra output row.")
    p.add_argument("--min-occurrences", type=int, default=1,
                   help="Minimum total occurrences required for output.")
    args = p.parse_args()

    species_sets: Dict[str, Set[str]] = defaultdict(set)
    genus_sets: Dict[str, Set[str]] = defaultdict(set)
    family_sets: Dict[str, Set[str]] = defaultdict(set)
    seq_sets: Dict[str, Set[str]] = defaultdict(set)
    counts: Counter = Counter()

    with open_text(args.kmers, "rt") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        required = {"kmer", "sequence_id", "species", "genus"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            sys.exit(f"[ERROR] missing required columns in k-mer table: {sorted(missing)}")

        for row in reader:
            kmer = row["kmer"].strip().upper()
            if not kmer:
                continue
            counts[kmer] += 1
            if clean_taxon(row.get("species", "")):
                species_sets[kmer].add(clean_taxon(row.get("species", "")))
            if clean_taxon(row.get("genus", "")):
                genus_sets[kmer].add(clean_taxon(row.get("genus", "")))
            if clean_taxon(row.get("family", "")):
                family_sets[kmer].add(clean_taxon(row.get("family", "")))
            if clean_taxon(row.get("sequence_id", "")):
                seq_sets[kmer].add(clean_taxon(row.get("sequence_id", "")))

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    if args.summary:
        Path(args.summary).parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "kmer", "specificity_rank", "family", "genus", "species",
        "n_occurrences", "n_families", "n_genera", "n_species", "n_sequences"
    ]

    n_species_specific = 0
    n_genus_specific = 0
    n_total = 0

    with open_text(args.out, "wt") as out:
        writer = csv.DictWriter(out, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        writer.writeheader()

        for kmer in sorted(counts):
            if counts[kmer] < args.min_occurrences:
                continue

            families = sorted(family_sets.get(kmer, set()))
            genera = sorted(genus_sets.get(kmer, set()))
            species = sorted(species_sets.get(kmer, set()))

            is_species = len(species) == 1
            is_genus = len(genera) == 1

            if is_species:
                writer.writerow({
                    "kmer": kmer,
                    "specificity_rank": "species_specific",
                    "family": ";".join(families),
                    "genus": ";".join(genera),
                    "species": ";".join(species),
                    "n_occurrences": counts[kmer],
                    "n_families": len(families),
                    "n_genera": len(genera),
                    "n_species": len(species),
                    "n_sequences": len(seq_sets.get(kmer, set())),
                })
                n_species_specific += 1
                n_total += 1

            if is_genus and (args.include_genus_even_if_species_specific or not is_species):
                writer.writerow({
                    "kmer": kmer,
                    "specificity_rank": "genus_specific",
                    "family": ";".join(families),
                    "genus": ";".join(genera),
                    "species": ";".join(species),
                    "n_occurrences": counts[kmer],
                    "n_families": len(families),
                    "n_genera": len(genera),
                    "n_species": len(species),
                    "n_sequences": len(seq_sets.get(kmer, set())),
                })
                n_genus_specific += 1
                n_total += 1

    if args.summary:
        with open_text(args.summary, "wt") as out:
            out.write("metric\tvalue\n")
            out.write(f"total_unique_kmers\t{len(counts)}\n")
            out.write(f"species_specific_rows\t{n_species_specific}\n")
            out.write(f"genus_specific_rows\t{n_genus_specific}\n")
            out.write(f"informative_rows_written\t{n_total}\n")

    print(f"[INFO] total unique k-mers : {len(counts)}", file=sys.stderr)
    print(f"[INFO] species-specific    : {n_species_specific}", file=sys.stderr)
    print(f"[INFO] genus-specific      : {n_genus_specific}", file=sys.stderr)
    print(f"[INFO] output              : {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
